linters:
  eslint:
    config: './.eslintrc'
  jscs:
    config: './.jshintrc'
  csslint: {  }
  phpcs:
    standard: PSR2
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
    - 'vendor/*'
